In [1]:
import pandas as pd

bp_details = pd.read_csv('bp_details.csv')
all_bp = pd.read_csv('all_bp.csv')
all_oscars = pd.read_csv('all_oscars.csv')
bp_nominees = pd.read_csv('bp_nominees.csv')

In [2]:
#take a look
bp_details.head()
#drop extra index
bp_details= bp_details.drop(columns={'Unnamed: 0'})
bp_details.head()

,title,runtime,rating,genre,summary,gross,year
0,Nomadland,107 min,R,Drama,"A woman in her sixties, after losing everythin...",NaN,2020
1,The Father,97 min,PG-13,"Drama, Mystery",A man refuses all assistance from his daughter...,NaN,2020
2,Judas and the Black Messiah,126 min,R,"Biography, Drama, History","Offered a plea deal by the FBI, William O'Neal...",NaN,2021
3,Mank,131 min,R,"Biography, Comedy, Drama",1930s Hollywood is re-evaluated through the ey...,NaN,2020
4,Minari,115 min,PG-13,Drama,A Korean family starts a farm in 1980s Arkansas.,NaN,2020

In [3]:
#all_bp = all_bp.drop(columns={'Unnamed: 0'})
all_bp = all_bp.query('year >= 1963')
all_bp = all_bp.query('year <= 2020')
all_bp

     Unnamed: 0      category                           nominee  year  winner
0          4944  Best Picture                Lawrence of Arabia  1963     1.0
1          4945  Best Picture                   The Longest Day  1963     0.0
2          4946  Best Picture  Meredith Willson's The Music Man  1963     0.0
3          4947  Best Picture              Mutiny on the Bounty  1963     0.0
4          4948  Best Picture             To Kill a Mockingbird  1963     0.0
..          ...           ...                               ...   ...     ...
328       13121  Best Picture                             Joker  2020     0.0
329       13122  Best Picture                      Little Women  2020     0.0
330       13123  Best Picture                    Marriage Story  2020     0.0
331       13124  Best Picture                              1917  2020     0.0
332       13125  Best Picture   Once upon a Time...in Hollywood  2020     0.0

[333 rows x 5 columns]

In [4]:
all_oscars = all_oscars.drop(columns={'Unnamed: 0'})
all_oscars.head()

  category              nominee  year  winner
0    Actor        Emil Jannings  1929     1.0
1    Actor  Richard Barthelmess  1929     0.0
2  Actress         Janet Gaynor  1929     1.0
3  Actress       Louise Dresser  1929     0.0
4  Actress       Gloria Swanson  1929     0.0

In [5]:
bp_nominees = bp_nominees.drop(columns={'Unnamed: 0'})
bp_nominees

,film,film_studio,film_studio/producer(s),producer(s),films,oscars_year
0,NaN,NaN,NaN,NaN,NaN,1927
1,Wings,Famous Players-Lasky,NaN,NaN,NaN,1927
2,7th Heaven,Fox,NaN,NaN,NaN,1927
3,The Racket,The Caddo Company,NaN,NaN,NaN,1927
4,NaN,NaN,NaN,NaN,NaN,1928
...,...,...,...,...,...,...
670,King Richard,NaN,NaN,"Tim White, Trevor White, and Will Smith",NaN,2021
671,Licorice Pizza,NaN,NaN,"Sara Murphy, Adam Somner, and Paul Thomas Ande...",NaN,2021
672,Nightmare Alley,NaN,NaN,"J. Miles Dale, Guillermo del Toro, and Bradley...",NaN,2021
673,The Power of the Dog,NaN,NaN,"Emile Sherman, Iain Canning, Roger Frappier, J...",NaN,2021
674,West Side Story,NaN,NaN,Steven Spielberg and Kristie Macosko Krieger,NaN,2021

In [6]:
#box office numbers and gross aren't available yet for 2020, Best Picture became a category in 1963, so narrow in on years 1963-2020
#schools.query('econ_disadv > 200')
bp_details = bp_details.query('year >= 1962')
bp_details = bp_details.query('year <= 2020')
bp_details

,title,runtime,rating,genre,summary,gross,year
0,Nomadland,107 min,R,Drama,"A woman in her sixties, after losing everythin...",NaN,2020
1,The Father,97 min,PG-13,"Drama, Mystery",A man refuses all assistance from his daughter...,NaN,2020
3,Mank,131 min,R,"Biography, Comedy, Drama",1930s Hollywood is re-evaluated through the ey...,NaN,2020
4,Minari,115 min,PG-13,Drama,A Korean family starts a farm in 1980s Arkansas.,NaN,2020
5,Promising Young Woman,113 min,R,"Crime, Drama, Mystery","A young woman, traumatized by a tragic event i...",NaN,2020
...,...,...,...,...,...,...,...
335,Lawrence of Arabia,218 min,Approved,"Adventure, Biography, Drama","The story of T.E. Lawrence, the English office...","44,824,144",1962
336,The Longest Day,178 min,G,"Action, Drama, History","The events of D-Day, told on a grand scale fro...","39,100,000",1962
337,The Music Man,151 min,G,"Comedy, Family, Musical",Traveling con artist Harold Hill targets the n...,"14,953,846",1962
338,Mutiny on the Bounty,178 min,Not Rated,"Adventure, Drama, History","In 1787, British ship Bounty leaves Portsmouth...","13,680,000",1962
339,To Kill a Mockingbird,129 min,Approved,"Crime, Drama","Atticus Finch, a widowed lawyer in Depression-...",NaN,1962

In [7]:
test = pd.merge(bp_details, all_bp, left_on='title', right_on='nominee', how='outer')
test.head(60)

,title,runtime,rating,genre,summary,gross,year_x,Unnamed: 0,category,nominee,year_y,winner
0,Nomadland,107 min,R,Drama,"A woman in her sixties, after losing everythin...",NaN,2020.0,NaN,NaN,NaN,NaN,NaN
1,The Father,97 min,PG-13,"Drama, Mystery",A man refuses all assistance from his daughter...,NaN,2020.0,NaN,NaN,NaN,NaN,NaN
2,Mank,131 min,R,"Biography, Comedy, Drama",1930s Hollywood is re-evaluated through the ey...,NaN,2020.0,NaN,NaN,NaN,NaN,NaN
3,Minari,115 min,PG-13,Drama,A Korean family starts a farm in 1980s Arkansas.,NaN,2020.0,NaN,NaN,NaN,NaN,NaN
4,Promising Young Woman,113 min,R,"Crime, Drama, Mystery","A young woman, traumatized by a tragic event i...",NaN,2020.0,NaN,NaN,NaN,NaN,NaN
5,Sound of Metal,120 min,R,"Drama, Music",A heavy-metal drummer's life is thrown into fr...,NaN,2019.0,NaN,NaN,NaN,NaN,NaN
6,The Trial of the Chicago,129 min,R,"Drama, History, Thriller",The story of 7 people on trial stemming from v...,NaN,2020.0,NaN,NaN,NaN,NaN,NaN
7,Parasite,132 min,R,"Comedy, Drama, Thriller",Greed and class discrimination threaten the ne...,"53,367,844",2019.0,13117.0,Best Picture,Parasite,2020.0,1.0
8,Ford v Ferrari,152 min,PG-13,"Action, Biography, Drama",American car designer Carroll Shelby and drive...,"117,624,028",2019.0,13118.0,Best Picture,Ford v Ferrari,2020.0,0.0
9,Joker,122 min,R,"Crime, Drama, Thriller",A mentally troubled stand-up comedian embarks ...,"335,451,311",2019.0,13121.0,Best Picture,Joker,2020.0,0.0
10,Marriage Story,137 min,R,"Drama, Romance",Noah Baumbach's incisive and compassionate loo...,"2,000,000",2019.0,13123.0,Best Picture,Marriage Story,2020.0,0.0
11,The Irishman,209 min,R,"Biography, Crime, Drama",Hitman Frank Sheeran looks back at the secrets...,"7,000,000",2019.0,13119.0,Best Picture,The Irishman,2020.0,0.0
12,Jojo Rabbit,108 min,PG-13,"Comedy, Drama, War",A young German boy in the Hitler Youth whose h...,"349,555",2019.0,13120.0,Best Picture,Jojo Rabbit,2020.0,0.0
13,Little Women,135 min,PG,"Drama, Romance","Jo March reflects back and forth on her life, ...","108,101,214",2019.0,13122.0,Best Picture,Little Women,2020.0,0.0
14,Once Upon a Time In Hollywood,161 min,R,"Comedy, Drama",A faded television actor and his stunt double ...,"142,502,728",2019.0,NaN,NaN,NaN,NaN,NaN
15,Green Book,130 min,PG-13,"Biography, Comedy, Drama",A working-class Italian-American bouncer becom...,"85,080,171",2018.0,12994.0,Best Picture,Green Book,2019.0,1.0
16,Black Panther,134 min,PG-13,"Action, Adventure, Sci-Fi","T'Challa, heir to the hidden but advanced king...","700,059,566",2018.0,12995.0,Best Picture,Black Panther,2019.0,0.0
17,BlacKkKlansman,135 min,R,"Biography, Comedy, Crime","Ron Stallworth, an African American police off...","49,275,340",2018.0,12996.0,Best Picture,BlacKkKlansman,2019.0,0.0
18,Bohemian Rhapsody,134 min,PG-13,"Biography, Drama, Music",The story of the legendary British rock band Q...,"216,428,042",2018.0,12997.0,Best Picture,Bohemian Rhapsody,2019.0,0.0
19,The Favourite,119 min,R,"Biography, Comedy, Drama","In early 18th-century England, the status quo ...","34,366,783",2018.0,12998.0,Best Picture,The Favourite,2019.0,0.0
20,Roma,135 min,R,Drama,A year in the life of a middle-class family's ...,NaN,2018.0,12999.0,Best Picture,Roma,2019.0,0.0
21,A Star Is Born,136 min,R,"Drama, Music, Romance",A musician helps a young singer find fame as a...,"215,288,866",2018.0,13000.0,Best Picture,A Star Is Born,2019.0,0.0
22,Vice,132 min,R,"Biography, Comedy, Drama","The story of Dick Cheney, an unassuming bureau...","47,836,282",2018.0,13001.0,Best Picture,Vice,2019.0,0.0
23,The Shape of Water,123 min,R,"Drama, Fantasy, Romance",At a top secret research facility in the 1960s...,"63,859,435",2017.0,12871.0,Best Picture,The Shape of Water,2018.0,1.0
24,Dunkirk,106 min,PG-13,"Action, Drama, History","Allied soldiers from Belgium, the British Comm...","188,373,161",2017.0,12874.0,Best Picture,Dunkirk,2018.0,0.0
25,"Three Billboards Outside Ebbing, Missouri",115 min,R,"Comedy, Crime, Drama",A mother personally challenges the local autho...,"54,513,740",2017.0,NaN,NaN,NaN,NaN,NaN
26,Lady Bird,94 min,R,"Comedy, Drama","In 2002, an artistically inclined seventeen-ye...","48,958,273",2017.0,12876.0,Best Picture,Lady Bird,2018.0,0.0
27,The Post,116 min,PG-13,Drama,A cover-up spanning four U.S. Presidents pushe...,"81,903,458",2017.0,12878.0,Best Picture,The Post,2018.0,0.0
28,Get Out,104 min,R,"Horror, Mystery, Thriller",A young African-American visits his white girl...,"176,040,665",2017.0,12875.0,Best Picture,Get Out,2018.0,0.0
29,Call Me by Your Name,132 min,R,"Drama, Romance","In 1980s Italy, romance blossoms between a sev...","18,095,701",2017.0,12872.0,Best Picture,Call Me by Your Name,2018.0,0.0
30,Darkest Hour,125 min,PG-13,"Biography, Drama, War","In May 1940, the fate of World War II hangs on...","56,468,410",2017.0,12873.0,Best Picture,Darkest Hour,2018.0,0.0
31,All the Money in the World,132 min,R,"Biography, Crime, Drama",The story of the kidnapping of 16-year-old Joh...,"25,106,315",2017.0,NaN,NaN,NaN,NaN,NaN
32,Moonlight,111 min,R,Drama,A young African-American man grapples with his...,"27,854,932",2016.0,12745.0,Best Picture,Moonlight,2017.0,1.0
33,Arrival,116 min,PG-13,"Drama, Mystery, Sci-Fi",A linguist works with the military to communic...,"100,546,139",2016.0,12746.0,Best Picture,Arrival,2017.0,0.0
34,Fences,139 min,PG-13,Drama,A working-class African-American father tries ...,"57,642,961",2016.0,12747.0,Best Picture,Fences,2017.0,0.0
35,Hacksaw Ridge,139 min,R,"Biography, Drama, History",World War II American Army Medic Desmond T. Do...,"67,209,615",2016.0,12748.0,Best Picture,Hacksaw Ridge,2017.0,0.0
36,Hell or High Water,102 min,R,"Crime, Drama, Thriller",A divorced father and his ex-con older brother...,"26,862,450",2016.0,12749.0,Best Picture,Hell or High Water,2017.0,0.0
37,Hidden Figures,127 min,PG,"Biography, Drama, History",The story of a team of female African-American...,"169,607,287",2016.0,12750.0,Best Picture,Hidden Figures,2017.0,0.0
38,La La Land,128 min,PG-13,"Comedy, Drama, Music","While navigating their careers in Los Angeles,...","151,101,803",2016.0,12751.0,Best Picture,La La Land,2017.0,0.0
39,Lion,118 min,PG-13,"Biography, Drama",A five-year-old Indian boy is adopted by an Au...,"51,739,495",2016.0,12752.0,Best Picture,Lion,2017.0,0.0
40,Manchester by the Sea,137 min,R,Drama,A depressed uncle is asked to take care of his...,"47,695,371",2016.0,12753.0,Best Picture,Manchester by the Sea,2017.0,0.0
41,Spotlight,129 min,R,"Biography, Crime, Drama",The true story of how the Boston Globe uncover...,"45,055,776",2015.0,12622.0,Best Picture,Spotlight,2016.0,1.0
42,The Big Short,130 min,R,"Biography, Comedy, Drama",In 2006-2007 a group of investors bet against ...,"70,259,870",2015.0,12623.0,Best Picture,The Big Short,2016.0,0.0
43,Bridge of Spies,142 min,PG-13,"Drama, History, Thriller","During the Cold War, an American lawyer is rec...","72,313,754",2015.0,12624.0,Best Picture,Bridge of Spies,2016.0,0.0
44,Brooklyn,117 min,PG-13,"Drama, Romance","An Irish immigrant lands in 1950s Brooklyn, wh...","38,322,743",2015.0,12625.0,Best Picture,Brooklyn,2016.0,0.0
45,Mad Max: Fury Road,120 min,R,"Action, Adventure, Sci-Fi","In a post-apocalyptic wasteland, a woman rebel...","154,058,340",2015.0,12626.0,Best Picture,Mad Max: Fury Road,2016.0,0.0
46,The Martian,144 min,PG-13,"Adventure, Drama, Sci-Fi",An astronaut becomes stranded on Mars after hi...,"228,433,663",2015.0,12627.0,Best Picture,The Martian,2016.0,0.0
47,The Revenant,156 min,R,"Action, Adventure, Drama",A frontiersman on a fur trading expedition in ...,"183,637,894",2015.0,12628.0,Best Picture,The Revenant,2016.0,0.0
48,Room,118 min,R,"Drama, Thriller","Held captive for 7 years in an enclosed space,...","14,677,674",2015.0,12629.0,Best Picture,Room,2016.0,0.0
49,Birdman or,119 min,R,"Comedy, Drama",A washed-up superhero actor attempts to revive...,"42,340,598",2014.0,NaN,NaN,NaN,NaN,NaN
50,American Sniper,133 min,R,"Action, Biography, Drama",Navy S.E.A.L. sniper Chris Kyle's pinpoint acc...,"350,126,372",2014.0,12502.0,Best Picture,American Sniper,2015.0,0.0
51,Boyhood,165 min,R,Drama,"The life of Mason, from early childhood to his...","25,379,975",2014.0,12503.0,Best Picture,Boyhood,2015.0,0.0
52,The Imitation Game,114 min,PG-13,"Biography, Drama, Thriller","During World War II, the English mathematical ...","91,125,683",2014.0,12505.0,Best Picture,The Imitation Game,2015.0,0.0
53,The Grand Budapest Hotel,99 min,R,"Adventure, Comedy, Crime",A writer encounters the owner of an aging high...,"59,100,318",2014.0,12504.0,Best Picture,The Grand Budapest Hotel,2015.0,0.0
54,Selma,128 min,PG-13,"Biography, Drama, History","A chronicle of Dr. Martin Luther King, Jr.'s c...","52,076,908",2014.0,12506.0,Best Picture,Selma,2015.0,0.0
55,The Theory of Everything,123 min,PG-13,"Biography, Drama, Romance",A look at the relationship between the famous ...,"35,893,537",2014.0,12507.0,Best Picture,The Theory of Everything,2015.0,0.0
56,Whiplash,106 min,R,"Drama, Music",A promising young drummer enrolls at a cut-thr...,"13,092,000",2014.0,12508.0,Best Picture,Whiplash,2015.0,0.0
57,Years a Slave,134 min,R,"Biography, Drama, History","In the antebellum United States, Solomon North...","56,671,993",2013.0,NaN,NaN,NaN,NaN,NaN
58,American Hustle,138 min,R,"Crime, Drama","A con man, Irving Rosenfeld, along with his se...","150,117,807",2013.0,12380.0,Best Picture,American Hustle,2014.0,0.0
59,Captain Phillips,134 min,PG-13,"Action, Biography, Crime",The true story of Captain Richard Phillips and...,"107,100,855",2013.0,12381.0,Best Picture,Captain Phillips,2014.0,0.0

In [8]:
test[test.title.isna()]

,title,runtime,rating,genre,summary,gross,year_x,Unnamed: 0,category,nominee,year_y,winner
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4946.0,Best Picture,Meredith Willson's The Music Man,1963.0,0.0
339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5231.0,Best Picture,Dr. Strangelove or: How I Learned to Stop Worr...,1965.0,0.0
340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5620.0,Best Picture,The Russians Are Coming The Russians Are Coming,1967.0,0.0
341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5622.0,Best Picture,Who's Afraid of Virginia Woolf?,1967.0,0.0
342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6260.0,Best Picture,M*A*S*H,1971.0,0.0
343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6673.0,Best Picture,Cries and Whispers,1974.0,0.0
344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6982.0,Best Picture,One Flew over the Cuckoo's Nest,1976.0,1.0
345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7617.0,Best Picture,Kramer vs. Kramer,1980.0,1.0
346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7897.0,Best Picture,Raiders of the Lost Ark,1982.0,0.0
347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8035.0,Best Picture,E.T. The Extra-Terrestrial,1983.0,0.0
348,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9129.0,Best Picture,Dances With Wolves,1991.0,1.0
349,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9132.0,Best Picture,"The Godfather, Part III",1991.0,0.0
350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9133.0,Best Picture,Good Fellas,1991.0,0.0
351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9892.0,Best Picture,Apollo 13,1996.0,0.0
352,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9894.0,Best Picture,The Postman (Il Postino),1996.0,0.0
353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10163.0,Best Picture,L.A. Confidential,1998.0,0.0
354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10755.0,Best Picture,Moulin Rouge,2002.0,0.0
355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11233.0,Best Picture,"Good Night, and Good Luck.",2006.0,0.0
356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11796.0,Best Picture,District 9,2010.0,0.0
357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11799.0,Best Picture,Precious: Based on the Novel 'Push' by Sapphire,2010.0,0.0
358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11954.0,Best Picture,127 Hours,2011.0,0.0
359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11956.0,Best Picture,Toy Story 3,2011.0,0.0
360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11958.0,Best Picture,Winter's Bone,2011.0,0.0
361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12260.0,Best Picture,Les Mis_rables,2013.0,0.0
362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12379.0,Best Picture,12 Years a Slave,2014.0,1.0
363,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12501.0,Best Picture,Birdman or (The Unexpected Virtue of Ignorance),2015.0,1.0
364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12877.0,Best Picture,Phantom Thread,2018.0,0.0
365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12879.0,Best Picture,"Three Billboards outside Ebbing, Missouri",2018.0,0.0
366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13124.0,Best Picture,1917,2020.0,0.0
367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13125.0,Best Picture,Once upon a Time...in Hollywood,2020.0,0.0

In [9]:
#test merge shows some titles are different in each database - 368 in outer merge vs 303 in inner merge - 338 in bp_details vs 333 in bp_nominees
#Music Man vs Meredith Wilson's Music Man
#Who's Afraid of Virginia Woolf (?)
#MASH no special *
#Cries and (&) Whispers
#1917 gone from bp_details (reg ex error)
#Precious
#birdman
#127 hours (regex error)
#Once (...) upon a time in Hollywood

In [10]:
bp_details = bp_details.sort_values(['year', 'title']).reset_index(drop=True)
bp_details

,title,runtime,rating,genre,summary,gross,year
0,How the West Was Won,164 min,G,Western,A family saga covering several decades of West...,"46,500,000",1962
1,Lawrence of Arabia,218 min,Approved,"Adventure, Biography, Drama","The story of T.E. Lawrence, the English office...","44,824,144",1962
2,Mutiny on the Bounty,178 min,Not Rated,"Adventure, Drama, History","In 1787, British ship Bounty leaves Portsmouth...","13,680,000",1962
3,The Longest Day,178 min,G,"Action, Drama, History","The events of D-Day, told on a grand scale fro...","39,100,000",1962
4,The Music Man,151 min,G,"Comedy, Family, Musical",Traveling con artist Harold Hill targets the n...,"14,953,846",1962
...,...,...,...,...,...,...,...
333,Minari,115 min,PG-13,Drama,A Korean family starts a farm in 1980s Arkansas.,NaN,2020
334,Nomadland,107 min,R,Drama,"A woman in her sixties, after losing everythin...",NaN,2020
335,Promising Young Woman,113 min,R,"Crime, Drama, Mystery","A young woman, traumatized by a tragic event i...",NaN,2020
336,The Father,97 min,PG-13,"Drama, Mystery",A man refuses all assistance from his daughter...,NaN,2020
337,The Trial of the Chicago,129 min,R,"Drama, History, Thriller",The story of 7 people on trial stemming from v...,NaN,2020

In [11]:
all_bp = all_bp.sort_values(['year', 'nominee']).reset_index(drop=True)
all_bp

     Unnamed: 0      category                           nominee  year  winner
0          4944  Best Picture                Lawrence of Arabia  1963     1.0
1          4946  Best Picture  Meredith Willson's The Music Man  1963     0.0
2          4947  Best Picture              Mutiny on the Bounty  1963     0.0
3          4945  Best Picture                   The Longest Day  1963     0.0
4          4948  Best Picture             To Kill a Mockingbird  1963     0.0
..          ...           ...                               ...   ...     ...
328       13122  Best Picture                      Little Women  2020     0.0
329       13123  Best Picture                    Marriage Story  2020     0.0
330       13125  Best Picture   Once upon a Time...in Hollywood  2020     0.0
331       13117  Best Picture                          Parasite  2020     1.0
332       13119  Best Picture                      The Irishman  2020     0.0

[333 rows x 5 columns]

In [12]:
pd.concat([bp_details, all_bp], axis=1)

,title,runtime,rating,genre,summary,gross,year,Unnamed: 0,category,nominee,year,winner
0,How the West Was Won,164 min,G,Western,A family saga covering several decades of West...,"46,500,000",1962,4944.0,Best Picture,Lawrence of Arabia,1963.0,1.0
1,Lawrence of Arabia,218 min,Approved,"Adventure, Biography, Drama","The story of T.E. Lawrence, the English office...","44,824,144",1962,4946.0,Best Picture,Meredith Willson's The Music Man,1963.0,0.0
2,Mutiny on the Bounty,178 min,Not Rated,"Adventure, Drama, History","In 1787, British ship Bounty leaves Portsmouth...","13,680,000",1962,4947.0,Best Picture,Mutiny on the Bounty,1963.0,0.0
3,The Longest Day,178 min,G,"Action, Drama, History","The events of D-Day, told on a grand scale fro...","39,100,000",1962,4945.0,Best Picture,The Longest Day,1963.0,0.0
4,The Music Man,151 min,G,"Comedy, Family, Musical",Traveling con artist Harold Hill targets the n...,"14,953,846",1962,4948.0,Best Picture,To Kill a Mockingbird,1963.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
333,Minari,115 min,PG-13,Drama,A Korean family starts a farm in 1980s Arkansas.,NaN,2020,NaN,NaN,NaN,NaN,NaN
334,Nomadland,107 min,R,Drama,"A woman in her sixties, after losing everythin...",NaN,2020,NaN,NaN,NaN,NaN,NaN
335,Promising Young Woman,113 min,R,"Crime, Drama, Mystery","A young woman, traumatized by a tragic event i...",NaN,2020,NaN,NaN,NaN,NaN,NaN
336,The Father,97 min,PG-13,"Drama, Mystery",A man refuses all assistance from his daughter...,NaN,2020,NaN,NaN,NaN,NaN,NaN
337,The Trial of the Chicago,129 min,R,"Drama, History, Thriller",The story of 7 people on trial stemming from v...,NaN,2020,NaN,NaN,NaN,NaN,NaN

In [13]:
test2 = pd.merge(bp_details, all_bp, left_on='title', right_on='nominee', how='inner')
test2 = test2.rename(columns={'year_x':'premiere_year', 'year_y':'oscar_year'})
test2

,title,runtime,rating,genre,summary,gross,premiere_year,Unnamed: 0,category,nominee,oscar_year,winner
0,How the West Was Won,164 min,G,Western,A family saga covering several decades of West...,"46,500,000",1962,5106,Best Picture,How the West Was Won,1964,0.0
1,Lawrence of Arabia,218 min,Approved,"Adventure, Biography, Drama","The story of T.E. Lawrence, the English office...","44,824,144",1962,4944,Best Picture,Lawrence of Arabia,1963,1.0
2,Mutiny on the Bounty,178 min,Not Rated,"Adventure, Drama, History","In 1787, British ship Bounty leaves Portsmouth...","13,680,000",1962,4947,Best Picture,Mutiny on the Bounty,1963,0.0
3,The Longest Day,178 min,G,"Action, Drama, History","The events of D-Day, told on a grand scale fro...","39,100,000",1962,4945,Best Picture,The Longest Day,1963,0.0
4,To Kill a Mockingbird,129 min,Approved,"Crime, Drama","Atticus Finch, a widowed lawyer in Depression-...",NaN,1962,4948,Best Picture,To Kill a Mockingbird,1963,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
298,Joker,122 min,R,"Crime, Drama, Thriller",A mentally troubled stand-up comedian embarks ...,"335,451,311",2019,13121,Best Picture,Joker,2020,0.0
299,Little Women,135 min,PG,"Drama, Romance","Jo March reflects back and forth on her life, ...","108,101,214",2019,13122,Best Picture,Little Women,2020,0.0
300,Marriage Story,137 min,R,"Drama, Romance",Noah Baumbach's incisive and compassionate loo...,"2,000,000",2019,13123,Best Picture,Marriage Story,2020,0.0
301,Parasite,132 min,R,"Comedy, Drama, Thriller",Greed and class discrimination threaten the ne...,"53,367,844",2019,13117,Best Picture,Parasite,2020,1.0
302,The Irishman,209 min,R,"Biography, Crime, Drama",Hitman Frank Sheeran looks back at the secrets...,"7,000,000",2019,13119,Best Picture,The Irishman,2020,0.0

!conda install -c conda-forge fuzzywuzzy

In [14]:
import difflib
from fuzzywuzzy import fuzz
from fuzzywuzzy import process

def fuzzy_merge(df_1, df_2, key1, key2, threshold=90, limit=2):

#df_1 is the left table to join
#df_2 is the right table to join
#key1 is the key column of the left table
#key2 is the key column of the right table
#threshold is how close the matches should be to return a match, based on Levenshtein distance
#limit is the amount of matches that will get returned, these are sorted high to low

    s = df_2[key2].tolist()

    m = df_1[key1].apply(lambda x: process.extract(x, s, limit=limit))    
    df_1['matches'] = m

    m2 = df_1['matches'].apply(lambda x: ', '.join([i[0] for i in x if i[1] >= threshold]))
    df_1['matches'] = m2

    return df_1

In [41]:
big_df = fuzzy_merge(bp_details, all_bp, 'title', 'nominee', threshold=90, limit=1)
big_df

,title,runtime,rating,genre,summary,gross,year,matches
0,How the West Was Won,164 min,G,Western,A family saga covering several decades of West...,"46,500,000",1962,How the West Was Won
1,Lawrence of Arabia,218 min,Approved,"Adventure, Biography, Drama","The story of T.E. Lawrence, the English office...","44,824,144",1962,Lawrence of Arabia
2,Mutiny on the Bounty,178 min,Not Rated,"Adventure, Drama, History","In 1787, British ship Bounty leaves Portsmouth...","13,680,000",1962,Mutiny on the Bounty
3,The Longest Day,178 min,G,"Action, Drama, History","The events of D-Day, told on a grand scale fro...","39,100,000",1962,The Longest Day
4,The Music Man,151 min,G,"Comedy, Family, Musical",Traveling con artist Harold Hill targets the n...,"14,953,846",1962,Meredith Willson's The Music Man
...,...,...,...,...,...,...,...,...
333,Minari,115 min,PG-13,Drama,A Korean family starts a farm in 1980s Arkansas.,NaN,2020,
334,Nomadland,107 min,R,Drama,"A woman in her sixties, after losing everythin...",NaN,2020,
335,Promising Young Woman,113 min,R,"Crime, Drama, Mystery","A young woman, traumatized by a tragic event i...",NaN,2020,
336,The Father,97 min,PG-13,"Drama, Mystery",A man refuses all assistance from his daughter...,NaN,2020,In the Name of the Father
337,The Trial of the Chicago,129 min,R,"Drama, History, Thriller",The story of 7 people on trial stemming from v...,NaN,2020,Chicago

In [42]:
everything = pd.merge(big_df, all_bp, left_on='matches', right_on='nominee', how='outer')

In [43]:
everything.query('nominee == "M*A*S*H"')

,title,runtime,rating,genre,summary,gross,year_x,matches,Unnamed: 0,category,nominee,year_y,winner
338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6260.0,Best Picture,M*A*S*H,1971.0,0.0